name: "PR Labeler"

on:
  pull_request_target:
    types: ["opened", "reopened", "ready_for_review"]

permissions:
  contents: read

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
      with:
        egress-policy: audit

    - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
    if: ${{ github.event.pull_request.draft == false && github.event.pull_request.user.login != 'bazel-io' }}
